
# Listening port for incoming connections
port: 5007

# desired amount of outgoing connections
outgoing: 2

# maximum amount of incoming connections
max_incoming: 10

# Preconfigured peers
Peers:
  -
    Hostname: localhost

  -
    Hostname: sers-mahlzeit.de
